services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:80"
    depends_on:
      - mongodb
    environment:
      - PORT=80
      - DATABASE=mongodb://admin:dwXJmJVrSvXpVUML@mongodb/mapApp?retryWrites=true&w=majority&appName=map-app&authSource=admin

  dashboard: 
    build:
      context: ./dashboard
    ports:
      - "3001:80"
    depends_on:
      - backend
    environment:
      - PORT=80
    
  mongodb:
    image: mongo:latest
    ports:
      - "4000:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: dwXJmJVrSvXpVUML
    volumes:
      - mongodb_data:/data/db
      
volumes:
  mongodb_data: